repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--skip-string-normalization]
#-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
#    sha: 1.3.9
#    hooks:
#    -   id: validate-html
